### ISSUE TITLE
Implement Bubble Sort Algorithm

### ISSUE THREAD

**Issue by sohamsshah** [codesONLY/JavaScriptONLY#26]
Add Bubble Sort Algorithm in JavaScript.
Refer: https://www.geeksforgeeks.org/bubble-sort-algorithms-by-using-javascript/

**Comment by supminn** [comment]
I would like to take this up.

**Comment by sohamsshah** [comment]
Thank you Supriya for your Interest. Sorry, this issue has been solved. Though, You can take up other open issues!😊
