### ISSUE TITLE
Renaming the Episode Markdown files of Namaste JavaScript.

### ISSUE THREAD

**Issue by amansharma007** [codesONLY/JavaScriptONLY#4]
It is a great effort to sum it all up in a list of markdown files. Great job, @sohamsshah 

While I was surfing through this, I found it difficult to find out the topics covered in each episode. I think to resolve this we can rename the Episode files according to the videos, like `E01 - Introduction`, etc.

What do you think @sohamsshah? If yes, I will create a PR for this.

**Comment by sohamsshah** [comment]
Yes @amansharma007  seems like a great addition. Thanks for your interest! Surely, would love your contributions :)
