### ISSUE TITLE
add blog on difference between splice and slice javascript method

### ISSUE THREAD

**Issue by Meghana-sk** [codesONLY/JavaScriptONLY#61]
Hi @sohamsshah , requesting you to assign me this issue

**Comment by sohamsshah** [comment]
Hi Meghana, currently we are looking for notes for [NamasteJS](https://www.youtube.com/watch?v=pN6jk0uUrD8&list=PLlasXeu85E9cQ32gLCvAvr9vNaUccPVNP) online YT series on JavaScript. Currently, there are few notes still pending; so I would encourage you to create issue for the same and add notes for it.

If you are willing to write blogs, you can write on hashnode.com or dev.to platforms. Thanks!
